[package]
name = "akasha-account"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/NahidaCollectingSite/akasha-account"

[lib]
path = "lib.rs"

[[bin]]
name = "akasha-account"
path = "main.rs"

[dependencies]
redb = "1.3.0"
